import numpy as np
a=np.array([[1,2], [3,4]])
print("The first matrix is: ")
print(a)
b=np.array([[5,6], [7,8]])
print("The second matrix is: ")
print(b)
c=np.add(a,b)
print("Matrix Addition")
print(c)